"""Feature 4.2 — the verification report as a real, shareable artifact.

Renders a rescue report as a clean, branded HTML document a compliance
officer can open, print to PDF, and forward to their boss. The signature
and chain head make it tamper-evident.
"""
from __future__ import annotations

import html


def render_html(report: dict) -> str:
    rows = ""
    for s in report["systems"]:
        if s["status"] == "ok":
            rows += (f"<tr><td>{html.escape(s['system'])}</td>"
                     f"<td class=num>{s['recovered']}</td>"
                     f"<td class=num>{s.get('quarantined_for_review',0)}</td>"
                     f"<td class=ok>recovered</td></tr>")
        else:
            rows += (f"<tr><td>{html.escape(s['system'])}</td><td class=num>0</td>"
                     f"<td class=num>—</td>"
                     f"<td class=bad>{html.escape(s.get('reason','failed'))}</td></tr>")
    c = report.get("cleaning") or {}
    clean_line = ""
    if c:
        clean_line = (f"{c['dedupe']['merged']} duplicates merged · "
                      f"{c['expire']['expired']} stale retired · "
                      f"{c['contradictions']['resolved']} contradictions resolved")
    counts = " · ".join(f"{k}: {v}" for k, v in report["vault_counts"].items())
    return f"""<!doctype html><html><head><meta charset=utf-8>
<title>MemoryVault Rescue Verification</title>
<style>
 body{{font:14px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;color:#12152a;
   max-width:760px;margin:40px auto;padding:0 24px}}
 .hd{{display:flex;align-items:center;gap:10px;border-bottom:3px solid #6b8afd;padding-bottom:14px}}
 .dot{{width:16px;height:16px;border-radius:50%;background:linear-gradient(135deg,#6b8afd,#8b6bfd)}}
 h1{{font-size:20px;margin:0}} .sub{{color:#667;margin:2px 0 0}}
 table{{width:100%;border-collapse:collapse;margin:18px 0}}
 th,td{{text-align:left;padding:9px 10px;border-bottom:1px solid #e6e8f2}}
 th{{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#889}}
 .num{{text-align:right;font-variant-numeric:tabular-nums}}
 .ok{{color:#1a9d5a;font-weight:600}} .bad{{color:#c0304a}}
 .box{{background:#f5f6fc;border:1px solid #e6e8f2;border-radius:10px;padding:14px 16px;margin:14px 0}}
 .big{{font-size:32px;font-weight:800}}
 .sig{{font-family:ui-monospace,monospace;font-size:11px;color:#556;word-break:break-all}}
 .pill{{display:inline-block;background:#e8f7ee;color:#1a9d5a;border-radius:20px;padding:3px 12px;font-size:12px;font-weight:600}}
 @media print{{body{{margin:0}}}}
</style></head><body>
 <div class=hd><span class=dot></span>
   <div><h1>Memory Rescue — Verification Report</h1>
   <div class=sub>Proof of what was recovered, from where, and that nothing was tampered with.</div></div></div>
 <div class=box><div class=big>{report['total_recovered']} memories recovered</div>
   <div class=sub>Started {report['started_at'][:19]} · Finished {report['finished_at'][:19]}</div>
   <div style="margin-top:8px">
     <span class=pill>Tamper check: {'PASSED' if report['chain_intact'] else 'FAILED'}</span></div></div>
 <table><tr><th>Source platform</th><th class=num>Recovered</th>
   <th class=num>Held for review</th><th>Status</th></tr>{rows}</table>
 {f'<div class=box><b>Cleaning pass:</b> {clean_line}</div>' if clean_line else ''}
 <div class=box><b>Vault state:</b> {counts}</div>
 <div class=box><b>Cryptographic signature</b> (binds this report to the
   tamper-evident event chain):<br><span class=sig>{report['signature']}</span><br>
   <b>Chain head:</b> <span class=sig>{report['chain_head']}</span></div>
 <p class=sub>Generated by MemoryVault. This document is verifiable: re-run
   the signature over the report body and compare to the value above.</p>
</body></html>"""
